### ISSUE TITLE
Mejoras Funcionales - Funcionamiento de rango de años en PROYECTO 

### ISSUE THREAD

**Issue by emilyb0** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-chikii#3]
El programa debe procesar archivos CSV descargados del SNIES que pueden tener variaciones en sus columnas a lo largo de los 📆 años. Los 📊 relevantes para analizar, sin importar la variación de columnas

**Comment by Santi12G** [comment]
Lo revisare

**Comment by Santi12G** [comment]
Falta aún hacer la revisión de la correctitud del código y su funcionamiento, aunque se cree que ya podría funcionar porque tiene en cuenta que las columnas que tienen las etiquetas de interés van siempre a variar de posición. La función que tiene esta solucion se llama procesarDatosCsv en el archivo SNIESController.cpp

**Comment by Santi12G** [comment]
Habia un error grandisimo en toda la logica que no se tuvo en cuenta que hay que modificar

**Comment by Santi12G** [comment]
Hay que hacer otro issue para indicar que este estuvo mal resuelto
